config/routes.rb
Rails.application.routes.draw do
  get 'users/users'

  get 'users/new'

  get 'users/index'

  get 'expenses/index'
  
  get 'expenses/new'

  
  get 'login' => 'login#login'

  get 'home/index'


  resources :expenses
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
    belongs_to :payer, class_name:"User", foreign_key: "user_id"
    has_and_belongs_to_many :beneficiaries, class_name:"User", foreign_key:"user_id"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :expenses
    has_and_belongs_to_many :donates, class_name: "Expense", foreign_key: "expense_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = Expense.all
  end

  def show
      @expense = Expense.find(params[:id])
      @payer = @expense.user_id
  end

  def new
    @users = User.all
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.beneficiary_ids = expense_params[:beneficiary_ids]
    @expense.save
    redirect_to @expense
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    redirect_to expenses_index_path
  end

  private

  def expense_params
    params.require(:expense).permit(:title, :amount, :user_id).merge( params.permit(beneficiary_ids: []) )
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Les Bons Amis"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def users
  end

  def index
      @users = User.all
  end
  

  def new
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def create
    @user = User.new(params.require(:user).permit(:id, :nom, :mot))
    @user.save
    redirect_to @user
  end

  def login
    @user = User.find(params[:id])

  end

  def show
    @user = User.find(params[:id])
  end

  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/expenses/index.html.erb
<div class="container">
    <h1>Toutes les dépenses :</h1>
    <div class="row">
        <table class="table">
        <tr id="tabBar" class="text-align">
            <th><p>Titre</p></th>
            <th ><p>Montant</p></th>
            <th ><p>Payeur</p></th>
            <th ><p>Bénéficiaire</p></th>
            <th ><p>Détails</p></th>
            <th ><p>Supprimer</p></th>
        </tr>
        
        <% @expenses.each do |expense| %>
            <tr id="tabResults">
                <td ><%= expense.title %></td>
                <td ><%= expense.amount %></td>
                <td ><%= expense.payer.nom %></td>
                <td >voir</td>
                <td><%= link_to 'Afficher', expense_path(expense) %></td>
                <td><%= link_to 'Destroy', expense_path(expense), method: :delete, data: { confirm:'Are you sure ?' }%></td>
            </tr>
        <% end %>
        </table>
    </div>
</div>

app/views/expenses/new.html.erb
<div class="container">
<div class="row">

<%= form_with scope: :expense, url:expenses_path, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control" %>
  </div>
 
 <div class="form-group">
    <%= form.label :montant %> (€)<br>
    <%= form.text_field :amount, class:"form-control" %>
 </div>


<div class="form-group">
    <%= form.label :payeur %><br>
   <%= form.select :user_id, @users.collect {|c| [c.nom, c.id]}%>
 </div>

<div class="form-group">
    <%= form.label :beneficiary_ids %><br>
    <%= form.select_tag :beneficiary_ids, options_from_collection_for_select(@users, 'id', 'nom'), {:multiple => true} %>    
 </div> 
 
  <p>
   <!-- <%= form.submit%>-->
   <%= button_tag(type:'submit', class:"btn") do %>
   <i class="icon-ok icon-white"></i> Save
    <% end %>
  </p>
<% end %>

</div>
</div>

app/views/expenses/show.html.erb
<div class="container">

<h1>Nouvelle dépense ajoutée :</h1>


    <div class="row">
        <p class="col-12">
        <strong>Titre : </strong>
        <%= @expense.title %>
        </p>
        
        <p class="col-12">
        <strong>Montant : </strong>
        <%= @expense.amount %> €
        </p>

         <p class="col-12">
        <strong>Payeur : </strong>
        <%= @expense.payer.nom %>
        </p>

         <p class="col-12">
        <strong>Beneficiaires : </strong>
        <% @expense.beneficiaries.each do |beneficiary|%>
            <%= beneficiary.nom %><br>
        <%end%>
        </p>

    </div>
</div>

app/views/home/index.html.erb
<h1 id="homeTitle"><%= @title %></h1>
<div id="divAddExpense" class="text-center">

<%= link_to "Ajouter une dépense !", new_expense_path, class:"btn" %>
<%= link_to "Ajouter un utilisateur !", new_user_path, class:"btn"  %>

  <!--  <button class="btn" href="/expense/new">Ajouter une dépense !</button>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>
</html>

app/views/login/login.html.erb
<h1>Se connecter</h1>
<label>Email</label><input></input>
<label>Mot de passe</label><input></input>

app/views/users/index.html.erb
<div class="container">
    <h1>Utilisateurs</h1>
    <div class="row">
        <table class="table">
        <tr id="tabBar" class="">
            <th class="">Nom</th>
            <th class="">Mot de passe</th>
            <th class="">Détails</th>
             <th class="">Supprimer</th>
        </tr>
        
        <% @users.each do |user| %>
            <tr>
            <td><%= user.nom %></td>
            <td><%= user.mot %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
             <td><%= link_to 'x', user_path(user), method:'delete' %></td>
            </tr>
        <% end %>
        </table>
    </div>
</div>

app/views/users/login.html.erb
<h1>Se connecter</h1>
<%= form_with scope: :user, url:users_path, local: true do |form| %>
  <p>
    <%= form.label :nom %><br>
    <%= form.text_field :nom %>
  </p>
 
  <p>
    <%= form.label :mot %> de passe<br>
    <%= form.text_field :mot %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Ajouter un utilisateur</h1>
<%= form_with scope: :user, url:users_path, local: true do |form| %>
  <p>
    <%= form.label :nom %><br>
    <%= form.text_field :nom %>
  </p>
 
  <p>
    <%= form.label :mot %> de passe<br>
    <%= form.text_field :mot %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Votre identifiant : </strong>
  <%= @user.nom %>
</p>
 
<p>
  <strong>Votre mot de passe : </strong>
  <%= @user.mot %>
</p>

app/views/users/users.html.erb
<h1>User#users</h1>
<p>Find me in app/views/user/users.html.erb</p>